############################################################
@local = https://localhost:6767
@deploy = https://

############################################################
### local test requests
POST {{local}}/getResponse
content-type: application/json

{
    "id": "gaga",
    "data": "111"
}

###
POST {{local}}/getProxyResponse
content-type: application/json

{
    "id": "gaga",
    "data": "111"
}

############################################################
### deployment requests
POST {{deploy}}/route
content-type: application/json

{
    "id": "gaga",
    "data": "111"
}